# Sample project demonstrating module output usage

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
}

# Use the global stamp module
module "global_stamp" {
  source = "../../"

  name     = "sampleapp"
  location = "East US"
  tags = {
    environment = "development"
    project     = "sample"
  }
  suffix = "dev"
}

# Example downstream module that uses the generated name
resource "azurerm_storage_account" "example" {
  name                = replace(module.global_stamp.name, "-", "")  # Storage accounts can't have hyphens
  resource_group_name = module.global_stamp.resource_group_name
  location            = "East US"

  account_tier             = "Standard"
  account_replication_type = "LRS"

  tags = {
    environment   = "development"
    project       = "sample"
    created_for   = module.global_stamp.name  # Using the generated name in tags
  }
}

# Output the generated name to demonstrate it's usable
output "generated_name" {
  description = "The name generated by the global stamp module"
  value       = module.global_stamp.name
}

output "storage_account_name" {
  description = "Storage account name derived from the generated name"
  value       = azurerm_storage_account.example.name
}

output "resource_group_used" {
  description = "Resource group name from the global stamp module"
  value       = module.global_stamp.resource_group_name
}
